# Generated by Django 5.2 on 2025-05-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateTimeField(null=True)),
                ('place_of_birth', models.DateTimeField(max_length=100)),
                ('Phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
