# Generated by Django 5.2 on 2025-05-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='DefaultFirstName', max_length=50),
        ),
    ]
